[project]
name = "session-8-ml-forecast-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mlflow>=3.7.0",
    "pip>=25.3",
]
